/**
 * @author Jagatheshwaran
 * 
 */
package seleniumBasics;

//import java.util.Set;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Getmethods {

	public static void main(String[] args) {

		// Provide the path of driver location
		System.setProperty("webdriver.firefox.marionette", "./BrowserDrivers/geckodriver.exe");

		// Driver instance is created
		WebDriver driver = new FirefoxDriver();

		// get - It will launch the browser with below url
		driver.get("https://www.google.co.in");

		// get page source - It will get the current page source
		String pagesource = driver.getPageSource();
		System.out.println(pagesource);

		// get current url - It will get the current page Url
		String url = driver.getCurrentUrl();
		System.out.println(url);

		// get title - It will get the current page Title
		String var = driver.getTitle();
		System.out.println(var);

		// get window handle - It will get the Alphanumeric Id generated by the driver instance for the window
		String window = driver.getWindowHandle();
		System.out.println(window);

	}

}
