package seleniumBasics;

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Handling_multiplebrowserwindows {

	public static void main(String[] args) {
		
		// provide your path of driver location
		System.setProperty("webdriver.firefox.marionette", "E:/ECLIPSE ENV//SELENIUM LIBS//geckodriver.exe");

		// Driver instance is created
		WebDriver driver = new FirefoxDriver();

		// Launching the browser with the below url
		driver.get("file:///E:/ECLIPSE%20ENV/SELENIUM%20LIBS/Login.html");

		driver.findElement(By.linkText("Sign Up")).click();

		// The line is used to captured the Alphanumeric id generated by the
		// driver instance for the browser window
		String parent = driver.getWindowHandle();

		// The line will store all the alphanumeric ids of the opened browsers
		Set<String> handles = driver.getWindowHandles();

		// The below line will give the number of browser windows
		int BrowserCount = handles.size();
		System.out.println(BrowserCount);

		// TO change focus to Second Window
		for (String s1 : handles) {
			if (!s1.equals(parent)) {
				driver.switchTo().window(s1);
				System.out.println(driver.getCurrentUrl());
				driver.close();
			}
		}

		driver.switchTo().window(parent);
		System.out.println(driver.getCurrentUrl());

	}

}
