/**
 * @author Jagatheshwaran
 * 
 */
package seleniumBasics;

//import java.util.Set;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Handling_GetMethod {

	public static void main(String[] args) {

		// Provide the path of driver location
		System.setProperty("webdriver.chrome.driver", "./BrowserDrivers/chromedriver.exe");

		// Driver instance is created
		WebDriver driver = new ChromeDriver();

		// To maximize Browser Window
		driver.manage().window().maximize();

		// get - It will launch the browser with below url
		driver.get("https://www.google.co.in");

		// get page source - It will get the current page source
		String pagesource = driver.getPageSource();
		System.out.println(pagesource);

		// get current url - It will get the current page Url
		String url = driver.getCurrentUrl();
		System.out.println(url);

		// get title - It will get the current page Title
		String var = driver.getTitle();
		System.out.println(var);

		// get window handle - It will get the Alphanumeric Id generated by the driver
		String window = driver.getWindowHandle();
		System.out.println(window);

		// It will close the Browser window
		driver.close();
	}

}
